// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FixedConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "202003282002033_FixedConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
